"Binding a socket to all network interfaces","Binding a socket to all interfaces opens it up to traffic from any IPv4 address and is therefore associated with security risks.","error","'' binds a socket to all interfaces.","/tests/servers/tests.py","256","9","256","23"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///django/views/static.py:19:26:19:38""]].","/django/views/static.py","37","8","37","15"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///django/views/static.py:19:26:19:38""]].","/django/views/static.py","41","12","41","19"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///django/views/static.py:19:26:19:38""]].","/django/views/static.py","44","15","44","22"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///django/views/static.py:19:26:19:38""]].","/django/views/static.py","50","29","50","36"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///django/contrib/admindocs/views.py:322:20:322:30""]].","/django/contrib/admindocs/views.py","333","20","333","32"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///django/contrib/admindocs/views.py:322:20:322:30""]].","/django/contrib/admindocs/views.py","334","41","334","53"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///django/contrib/admindocs/views.py:322:20:322:30""]].","/django/contrib/admindocs/views.py","339","31","339","43"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///tests/file_uploads/views.py:56:30:56:36""]].","/tests/file_uploads/views.py","65","45","65","53"
"Reflected server-side cross-site scripting","Writing user input directly to a web page allows for a cross-site scripting vulnerability.","error","Cross-site scripting vulnerability due to a [[""user-provided value""|""relative:///tests/asgi/urls.py:5:11:5:17""]].","/tests/asgi/urls.py","7","25","7","42"
"Reflected server-side cross-site scripting","Writing user input directly to a web page allows for a cross-site scripting vulnerability.","error","Cross-site scripting vulnerability due to a [[""user-provided value""|""relative:///tests/admin_views/views.py:6:17:6:23""]].","/tests/admin_views/views.py","7","25","7","43"
"Reflected server-side cross-site scripting","Writing user input directly to a web page allows for a cross-site scripting vulnerability.","error","Cross-site scripting vulnerability due to a [[""user-provided value""|""relative:///tests/admin_views/views.py:11:18:11:24""]].","/tests/admin_views/views.py","12","25","12","43"
"Reflected server-side cross-site scripting","Writing user input directly to a web page allows for a cross-site scripting vulnerability.","error","Cross-site scripting vulnerability due to a [[""user-provided value""|""relative:///tests/test_client_regress/views.py:46:33:46:36""]].","/tests/test_client_regress/views.py","56","29","56","46"
"Reflected server-side cross-site scripting","Writing user input directly to a web page allows for a cross-site scripting vulnerability.","error","Cross-site scripting vulnerability due to a [[""user-provided value""|""relative:///tests/test_client_regress/views.py:91:26:91:32""]].","/tests/test_client_regress/views.py","93","25","93","61"
"Reflected server-side cross-site scripting","Writing user input directly to a web page allows for a cross-site scripting vulnerability.","error","Cross-site scripting vulnerability due to a [[""user-provided value""|""relative:///tests/test_client_regress/views.py:127:19:127:25""]].","/tests/test_client_regress/views.py","129","25","129","98"
"Reflected server-side cross-site scripting","Writing user input directly to a web page allows for a cross-site scripting vulnerability.","error","Cross-site scripting vulnerability due to a [[""user-provided value""|""relative:///tests/test_client_regress/views.py:132:10:132:16""]].","/tests/test_client_regress/views.py","134","25","134","36"
"Reflected server-side cross-site scripting","Writing user input directly to a web page allows for a cross-site scripting vulnerability.","error","Cross-site scripting vulnerability due to a [[""user-provided value""|""relative:///tests/test_client_regress/views.py:137:14:137:20""]].","/tests/test_client_regress/views.py","139","25","139","38"
"Reflected server-side cross-site scripting","Writing user input directly to a web page allows for a cross-site scripting vulnerability.","error","Cross-site scripting vulnerability due to a [[""user-provided value""|""relative:///tests/test_client_regress/views.py:142:17:142:23""]].","/tests/test_client_regress/views.py","144","25","144","43"
"Reflected server-side cross-site scripting","Writing user input directly to a web page allows for a cross-site scripting vulnerability.","error","Cross-site scripting vulnerability due to a [[""user-provided value""|""relative:///tests/servers/views.py:49:17:49:23""]].","/tests/servers/views.py","50","25","50","38"
"Reflected server-side cross-site scripting","Writing user input directly to a web page allows for a cross-site scripting vulnerability.","error","Cross-site scripting vulnerability due to a [[""user-provided value""|""relative:///tests/test_client/views.py:372:17:372:23""]].","/tests/test_client/views.py","374","25","374","48"
"Information exposure through an exception","Leaking information about an exception, such as messages and stack traces, to an external user can expose implementation details that are useful to an attacker for developing a subsequent exploit.","error","[[""Stack trace information""|""relative:///django/core/handlers/asgi.py:218:17:218:38""]] flows to this location and may be exposed to an external user.","/django/core/handlers/asgi.py","218","17","218","85"
"Clear-text logging of sensitive information","Logging sensitive information without encryption or hashing can expose it to an attacker.","error","This expression logs [[""sensitive data (password)""|""relative:///django/db/backends/oracle/creation.py:242:28:242:77""]] as clear text.
This expression logs [[""sensitive data (password)""|""relative:///django/db/backends/oracle/creation.py:242:28:242:77""]] as clear text.
This expression logs [[""sensitive data (password)""|""relative:///django/db/backends/oracle/creation.py:341:20:341:54""]] as clear text.
This expression logs [[""sensitive data (password)""|""relative:///django/db/backends/oracle/creation.py:344:24:344:51""]] as clear text.","/django/db/backends/oracle/creation.py","275","23","275","26"
"Clear-text logging of sensitive information","Logging sensitive information without encryption or hashing can expose it to an attacker.","error","This expression logs [[""sensitive data (password)""|""relative:///django/db/backends/oracle/creation.py:341:20:341:54""]] as clear text.
This expression logs [[""sensitive data (password)""|""relative:///django/db/backends/oracle/creation.py:344:24:344:51""]] as clear text.","/django/db/backends/base/creation.py","31","26","31","41"
"Clear-text storage of sensitive information","Sensitive information stored without encryption or hashing can expose it to an attacker.","error","This expression stores [[""sensitive data (secret)""|""relative:///django/middleware/csrf.py:71:12:71:54""]] as clear text.
This expression stores [[""sensitive data (secret)""|""relative:///django/middleware/csrf.py:86:39:86:70""]] as clear text.
This expression stores [[""sensitive data (secret)""|""relative:///django/middleware/csrf.py:118:16:118:41""]] as clear text.","/django/middleware/csrf.py","188","17","188","43"
"Clear-text storage of sensitive information","Sensitive information stored without encryption or hashing can expose it to an attacker.","error","This expression stores [[""sensitive data (secret)""|""relative:///django/middleware/csrf.py:71:12:71:54""]] as clear text.
This expression stores [[""sensitive data (secret)""|""relative:///django/middleware/csrf.py:86:39:86:70""]] as clear text.
This expression stores [[""sensitive data (secret)""|""relative:///django/middleware/csrf.py:118:16:118:41""]] as clear text.","/django/http/response.py","169","29","169","33"
"Use of a broken or weak cryptographic hashing algorithm on sensitive data","Using broken or weak cryptographic hashing algorithms can compromise security.","warning","[[""Sensitive data (password)""|""relative:///django/contrib/auth/hashers.py:473:22:473:29""]] is used in a hashing algorithm (SHA1) that is insecure for password hashing, since it is not a computationally expensive hash function.
[[""Sensitive data (password)""|""relative:///django/contrib/auth/hashers.py:479:22:479:29""]] is used in a hashing algorithm (SHA1) that is insecure for password hashing, since it is not a computationally expensive hash function.","/django/contrib/auth/hashers.py","476","29","476","54"
"Use of a broken or weak cryptographic hashing algorithm on sensitive data","Using broken or weak cryptographic hashing algorithms can compromise security.","warning","[[""Sensitive data (password)""|""relative:///django/contrib/auth/hashers.py:504:22:504:29""]] is used in a hashing algorithm (MD5) that is insecure for password hashing, since it is not a computationally expensive hash function.
[[""Sensitive data (password)""|""relative:///django/contrib/auth/hashers.py:510:22:510:29""]] is used in a hashing algorithm (MD5) that is insecure for password hashing, since it is not a computationally expensive hash function.","/django/contrib/auth/hashers.py","507","28","507","53"
"Use of a broken or weak cryptographic hashing algorithm on sensitive data","Using broken or weak cryptographic hashing algorithms can compromise security.","warning","[[""Sensitive data (password)""|""relative:///django/contrib/auth/hashers.py:543:22:543:29""]] is used in a hashing algorithm (SHA1) that is insecure for password hashing, since it is not a computationally expensive hash function.
[[""Sensitive data (password)""|""relative:///django/contrib/auth/hashers.py:548:22:548:29""]] is used in a hashing algorithm (SHA1) that is insecure for password hashing, since it is not a computationally expensive hash function.","/django/contrib/auth/hashers.py","545","29","545","45"
"Use of a broken or weak cryptographic hashing algorithm on sensitive data","Using broken or weak cryptographic hashing algorithms can compromise security.","warning","[[""Sensitive data (password)""|""relative:///django/contrib/auth/hashers.py:580:22:580:29""]] is used in a hashing algorithm (MD5) that is insecure for password hashing, since it is not a computationally expensive hash function.
[[""Sensitive data (password)""|""relative:///django/contrib/auth/hashers.py:584:22:584:29""]] is used in a hashing algorithm (MD5) that is insecure for password hashing, since it is not a computationally expensive hash function.","/django/contrib/auth/hashers.py","582","28","582","44"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///django/views/generic/base.py:183:16:183:27""]].","/django/views/generic/base.py","186","16","186","18"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///django/views/generic/base.py:183:16:183:27""]].","/django/views/generic/base.py","192","54","192","56"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///django/views/generic/base.py:183:16:183:27""]].","/django/views/generic/base.py","194","45","194","47"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///django/contrib/auth/views.py:71:23:71:34""]].
Untrusted URL redirection depends on a [[""user-provided value""|""relative:///django/contrib/auth/views.py:73:13:73:24""]].","/django/views/generic/edit.py","57","37","57","58"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///django/views/i18n.py:23:18:23:24""]].","/django/views/i18n.py","52","37","52","44"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///django/views/i18n.py:23:18:23:24""]].","/django/views/i18n.py","59","53","59","62"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///tests/test_client_regress/views.py:74:47:74:53""]].","/tests/test_client_regress/views.py","77","33","77","99"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///django/contrib/contenttypes/views.py:9:14:9:20""]].","/django/contrib/contenttypes/views.py","86","37","86","83"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///django/contrib/flatpages/views.py:22:14:22:20""]].","/django/contrib/flatpages/views.py","42","50","42","69"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///django/contrib/auth/views.py:71:23:71:34""]].
Untrusted URL redirection depends on a [[""user-provided value""|""relative:///django/contrib/auth/views.py:73:13:73:24""]].","/django/contrib/auth/views.py","62","41","62","51"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///django/contrib/auth/views.py:71:23:71:34""]].
Untrusted URL redirection depends on a [[""user-provided value""|""relative:///django/contrib/auth/views.py:73:13:73:24""]].","/django/contrib/auth/views.py","80","16","80","49"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///django/contrib/auth/views.py:71:23:71:34""]].
Untrusted URL redirection depends on a [[""user-provided value""|""relative:///django/contrib/auth/views.py:73:13:73:24""]].","/django/contrib/auth/views.py","93","37","93","58"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///django/contrib/auth/views.py:139:25:139:36""]].
Untrusted URL redirection depends on a [[""user-provided value""|""relative:///django/contrib/auth/views.py:141:17:141:28""]].
Untrusted URL redirection depends on a [[""user-provided value""|""relative:///django/contrib/auth/views.py:151:29:151:40""]].","/django/contrib/auth/views.py","122","41","122","49"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///django/contrib/auth/views.py:280:36:280:47""]].","/django/contrib/auth/views.py","281","49","281","60"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///tests/test_client/views.py:135:37:135:43""]].
Untrusted URL redirection depends on a [[""user-provided value""|""relative:///tests/test_client/views.py:139:37:139:43""]].","/tests/test_client/views.py","132","33","132","43"
"XML internal entity expansion","Parsing user input as an XML document with arbitrary internal entity expansion is vulnerable to denial-of-service attacks.","warning","XML parsing depends on a [[""user-provided value""|""relative:///tests/test_client/views.py:104:19:104:25""]] without guarding against uncontrolled entity expansion.","/tests/test_client/views.py","108","28","108","39"
"Full server-side request forgery","Making a network request to a URL that is fully user-controlled allows for request forgery attacks.","error","The full URL of this request depends on a [[""user-provided value""|""relative:///tests/servers/views.py:36:26:36:32""]].","/tests/servers/views.py","37","10","37","50"
"Full server-side request forgery","Making a network request to a URL that is fully user-controlled allows for request forgery attacks.","error","The full URL of this request depends on a [[""user-provided value""|""relative:///tests/servers/views.py:41:39:41:45""]].","/tests/servers/views.py","42","10","42","64"
"Full server-side request forgery","Making a network request to a URL that is fully user-controlled allows for request forgery attacks.","error","The full URL of this request depends on a [[""user-provided value""|""relative:///tests/servers/views.py:41:39:41:45""]].","/tests/servers/views.py","44","10","44","53"
