"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///examples/example_plugin/example_plugin/api/views.py:44:49:44:60""]].","/examples/example_plugin/example_plugin/api/views.py","44","13","44","104"
"Information exposure through an exception","Leaking information about an exception, such as messages and stack traces, to an external user can expose implementation details that are useful to an attacker for developing a subsequent exploit.","error","[[""Stack trace information""|""relative:///nautobot/ipam/api/fields.py:16:43:16:43""]] flows to this location and may be exposed to an external user.","/nautobot/ipam/api/fields.py","17","47","17","47"
"Information exposure through an exception","Leaking information about an exception, such as messages and stack traces, to an external user can expose implementation details that are useful to an attacker for developing a subsequent exploit.","error","[[""Stack trace information""|""relative:///nautobot/core/api/mixins.py:94:30:94:30""]] flows to this location and may be exposed to an external user.","/nautobot/core/api/mixins.py","95","35","95","35"
"Information exposure through an exception","Leaking information about an exception, such as messages and stack traces, to an external user can expose implementation details that are useful to an attacker for developing a subsequent exploit.","error","[[""Stack trace information""|""relative:///nautobot/core/api/parsers.py:60:29:60:31""]] flows to this location and may be exposed to an external user.","/nautobot/core/api/parsers.py","61","30","61","37"
"Information exposure through an exception","Leaking information about an exception, such as messages and stack traces, to an external user can expose implementation details that are useful to an attacker for developing a subsequent exploit.","error","[[""Stack trace information""|""relative:///nautobot/core/api/serializers.py:800:34:800:34""]] flows to this location and may be exposed to an external user.","/nautobot/core/api/serializers.py","801","39","801","39"
"Information exposure through an exception","Leaking information about an exception, such as messages and stack traces, to an external user can expose implementation details that are useful to an attacker for developing a subsequent exploit.","error","[[""Stack trace information""|""relative:///nautobot/core/api/serializers.py:937:45:937:49""]] flows to this location and may be exposed to an external user.","/nautobot/core/api/serializers.py","938","39","938","48"
"Information exposure through an exception","Leaking information about an exception, such as messages and stack traces, to an external user can expose implementation details that are useful to an attacker for developing a subsequent exploit.","error","[[""Stack trace information""|""relative:///nautobot/core/api/serializers.py:957:45:957:49""]] flows to this location and may be exposed to an external user.","/nautobot/core/api/serializers.py","958","39","958","48"
"Information exposure through an exception","Leaking information about an exception, such as messages and stack traces, to an external user can expose implementation details that are useful to an attacker for developing a subsequent exploit.","error","[[""Stack trace information""|""relative:///nautobot/extras/api/serializers.py:560:37:560:37""]] flows to this location and may be exposed to an external user.
[[""Stack trace information""|""relative:///nautobot/extras/api/serializers.py:560:37:560:37""]] flows to this location and may be exposed to an external user.
[[""Stack trace information""|""relative:///nautobot/extras/api/serializers.py:560:37:560:37""]] flows to this location and may be exposed to an external user.
[[""Stack trace information""|""relative:///nautobot/extras/api/serializers.py:560:37:560:37""]] flows to this location and may be exposed to an external user.","/nautobot/extras/api/serializers.py","561","55","561","68"
"Information exposure through an exception","Leaking information about an exception, such as messages and stack traces, to an external user can expose implementation details that are useful to an attacker for developing a subsequent exploit.","error","[[""Stack trace information""|""relative:///nautobot/extras/api/serializers.py:602:37:602:37""]] flows to this location and may be exposed to an external user.
[[""Stack trace information""|""relative:///nautobot/extras/api/serializers.py:602:37:602:37""]] flows to this location and may be exposed to an external user.
[[""Stack trace information""|""relative:///nautobot/extras/api/serializers.py:602:37:602:37""]] flows to this location and may be exposed to an external user.
[[""Stack trace information""|""relative:///nautobot/extras/api/serializers.py:602:37:602:37""]] flows to this location and may be exposed to an external user.","/nautobot/extras/api/serializers.py","603","55","603","78"
"Information exposure through an exception","Leaking information about an exception, such as messages and stack traces, to an external user can expose implementation details that are useful to an attacker for developing a subsequent exploit.","error","[[""Stack trace information""|""relative:///nautobot/core/api/utils.py:197:32:197:45""]] flows to this location and may be exposed to an external user.","/nautobot/core/api/utils.py","204","25","204","28"
"Information exposure through an exception","Leaking information about an exception, such as messages and stack traces, to an external user can expose implementation details that are useful to an attacker for developing a subsequent exploit.","error","[[""Stack trace information""|""relative:///nautobot/extras/api/views.py:1016:31:1016:31""]] flows to this location and may be exposed to an external user.","/nautobot/extras/api/views.py","1019","25","1019","32"
"Information exposure through an exception","Leaking information about an exception, such as messages and stack traces, to an external user can expose implementation details that are useful to an attacker for developing a subsequent exploit.","error","[[""Stack trace information""|""relative:///nautobot/dcim/api/views.py:509:29:509:29""]] flows to this location and may be exposed to an external user.","/nautobot/dcim/api/views.py","510","38","510","85"
"Clear-text logging of sensitive information","Logging sensitive information without encryption or hashing can expose it to an attacker.","error","This expression logs [[""sensitive data (password)""|""relative:///nautobot/generate_secret_key.py:10:16:10:71""]] as clear text.","/nautobot/generate_secret_key.py","13","7","13","14"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///nautobot/core/views/generic.py:405:20:405:26""]].","/nautobot/core/views/generic.py","431","41","431","43"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///nautobot/core/views/generic.py:405:20:405:26""]].","/nautobot/core/views/generic.py","433","37","433","59"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///nautobot/core/views/generic.py:581:20:581:26""]].","/nautobot/core/views/generic.py","624","41","624","52"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///nautobot/core/views/generic.py:681:20:681:26""]].","/nautobot/core/views/generic.py","759","37","759","59"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///nautobot/core/views/generic.py:1328:20:1328:26""]].","/nautobot/core/views/generic.py","1379","41","1379","63"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///nautobot/ipam/views.py:913:20:913:26""]].","/nautobot/ipam/views.py","919","29","919","57"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///nautobot/users/views.py:261:20:261:26""]].","/nautobot/users/views.py","278","33","278","44"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///nautobot/dcim/views.py:2623:20:2623:26""]].","/nautobot/dcim/views.py","2640","37","2640","59"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///nautobot/extras/views.py:388:20:388:26""]].","/nautobot/extras/views.py","426","41","426","43"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///nautobot/extras/views.py:388:20:388:26""]].","/nautobot/extras/views.py","428","37","428","59"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///nautobot/extras/views.py:618:20:618:26""]].","/nautobot/extras/views.py","664","41","664","43"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///nautobot/extras/views.py:618:20:618:26""]].","/nautobot/extras/views.py","666","37","666","59"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///nautobot/extras/views.py:916:20:916:26""]].
Untrusted URL redirection depends on a [[""user-provided value""|""relative:///nautobot/extras/views.py:921:20:921:26""]].","/nautobot/extras/views.py","907","25","907","47"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///nautobot/extras/views.py:1555:20:1555:26""]].","/nautobot/extras/views.py","1567","25","1567","50"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///nautobot/extras/views.py:2013:20:2013:26""]].","/nautobot/extras/views.py","2049","41","2049","43"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///nautobot/extras/views.py:2013:20:2013:26""]].","/nautobot/extras/views.py","2051","37","2051","59"
