/tmp/urllib3/dummyserver/server.py:46:18: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/src/urllib3/contrib/pyopenssl.py:84:5: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/src/urllib3/contrib/pyopenssl.py:85:5: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/src/urllib3/contrib/securetransport.py:138:26: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/src/urllib3/contrib/securetransport.py:143:26: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/src/urllib3/contrib/securetransport.py:760:35: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/src/urllib3/contrib/securetransport.py:803:55: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/src/urllib3/util/retry.py:301:30: DUO102 insecure use of "random" module, prefer "random.SystemRandom"
/tmp/urllib3/test/conftest.py:307:31: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/test/test_exceptions.py:44:18: DUO103 insecure use of "pickle" or "cPickle"
/tmp/urllib3/test/test_ssl.py:173:32: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/test/test_util.py:643:13: DUO131 "urllib3" warnings disabled, insecure connections possible
/tmp/urllib3/test/test_util.py:975:14: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/test/test_util.py:975:29: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/test/test_util.py:992:14: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/test/test_util.py:992:35: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/test/with_dummyserver/test_https.py:378:14: DUO132 "urllib3" certificate verification disabled, insecure connections possible
/tmp/urllib3/test/with_dummyserver/test_https.py:381:23: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/test/with_dummyserver/test_https.py:396:14: DUO132 "urllib3" certificate verification disabled, insecure connections possible
/tmp/urllib3/test/with_dummyserver/test_https.py:531:14: DUO132 "urllib3" certificate verification disabled, insecure connections possible
/tmp/urllib3/test/with_dummyserver/test_https.py:545:14: DUO132 "urllib3" certificate verification disabled, insecure connections possible
/tmp/urllib3/test/with_dummyserver/test_https.py:606:14: DUO132 "urllib3" certificate verification disabled, insecure connections possible
/tmp/urllib3/test/with_dummyserver/test_https.py:619:14: DUO132 "urllib3" certificate verification disabled, insecure connections possible
/tmp/urllib3/test/with_dummyserver/test_https.py:779:46: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/test/with_dummyserver/test_https.py:844:31: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/test/with_dummyserver/test_no_ssl.py:26:14: DUO132 "urllib3" certificate verification disabled, insecure connections possible
/tmp/urllib3/test/with_dummyserver/test_proxy_poolmanager.py:660:24: DUO130 insecure use of "hashlib" module
/tmp/urllib3/test/with_dummyserver/test_socketlevel.py:150:33: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/test/with_dummyserver/test_socketlevel.py:151:24: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/test/with_dummyserver/test_socketlevel.py:211:25: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/test/with_dummyserver/test_socketlevel.py:1272:14: DUO132 "urllib3" certificate verification disabled, insecure connections possible
