/tmp/MLAlchemy/mlalchemy/parser.py:36:24: DUO109 insecure use of "yaml" parsing function, prefer "safe_*" equivalent
/tmp/MLAlchemy/mlalchemy/utils.py:18:23: DUO138 catastrophic "re" usage - denial-of-service possible
/tmp/MLAlchemy/mlalchemy/utils.py:21:23: DUO138 catastrophic "re" usage - denial-of-service possible
