/tmp/mistune/mistune/block_parser.py:59:22: DUO138 catastrophic "re" usage - denial-of-service possible
/tmp/mistune/mistune/block_parser.py:343:17: DUO138 catastrophic "re" usage - denial-of-service possible
/tmp/mistune/mistune/directives/base.py:24:21: DUO138 catastrophic "re" usage - denial-of-service possible
